# Generated by Django 5.0.3 on 2024-04-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather_forecast", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CityName",
            new_name="City",
        ),
        migrations.RenameField(
            model_name="city",
            old_name="name_city",
            new_name="name",
        ),
    ]
