# Generated by Django 5.0.3 on 2024-04-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather_forecast", "0002_rename_cityname_city_rename_name_city_city_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Введите город", max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name="City",
        ),
    ]
