# Generated by Django 5.0.2 on 2024-03-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Artiles",
            new_name="Articles",
        ),
        migrations.AlterModelOptions(
            name="articles",
            options={"verbose_name": "Новость", "verbose_name_plural": "Новости"},
        ),
    ]
